{
  "name": "Form1",
  "caption": "Curl Example - HTTP Client",
  "width": 70,
  "height": 24,
  "foreColor": 0,
  "backColor": 7,
  "controls": [
    {
      "id": 1,
      "type": 2,
      "name": "lblTitle",
      "caption": "HTTP Client Example",
      "x": 2,
      "y": 1,
      "width": 25,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 2,
      "type": 2,
      "name": "lblURL",
      "caption": "URL:",
      "x": 2,
      "y": 3,
      "width": 5,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 3,
      "type": 3,
      "name": "txtURL",
      "caption": "",
      "x": 8,
      "y": 3,
      "width": 50,
      "height": 1,
      "foreColor": 0,
      "backColor": 15,
      "tabIndex": 1,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 4,
      "type": 1,
      "name": "btnFetch",
      "caption": "Fetch",
      "x": 60,
      "y": 3,
      "width": 8,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 2,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 5,
      "type": 2,
      "name": "lblStatus",
      "caption": "Status: Ready",
      "x": 2,
      "y": 5,
      "width": 40,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 6,
      "type": 2,
      "name": "lblResponse",
      "caption": "Response:",
      "x": 2,
      "y": 7,
      "width": 10,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 7,
      "type": 12,
      "name": "txtResponse",
      "caption": "",
      "x": 2,
      "y": 8,
      "width": 66,
      "height": 14,
      "foreColor": 0,
      "backColor": 15,
      "tabIndex": 3,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 8,
      "type": 23,
      "name": "curlClient",
      "caption": "",
      "x": 0,
      "y": 0,
      "width": 3,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": false,
      "url": "https://httpbin.org/get",
      "httpMethod": "GET"
    }
  ],
  "code": "' Curl Example - HTTP Client Demo\n' Demonstrates using the Curl widget to fetch data from URLs\n\nSUB Form_Load()\n    ' Set default URL\n    txtURL.SetValue(\"https://httpbin.org/get\")\n    lblStatus_Text = \"Status: Ready - Enter a URL and click Fetch\"\nEND SUB\n\nSUB btnFetch_Click()\n    ' Get the URL from the textbox\n    DIM url AS STRING = txtURL.Value()\n    \n    IF url = \"\" THEN\n        lblStatus_Text = \"Status: Error - Please enter a URL\"\n        RETURN\n    ENDIF\n    \n    lblStatus_Text = \"Status: Fetching...\"\n    \n    ' Perform the HTTP request using CurlGet helper\n    DIM response AS STRING\n    DIM statusCode AS INTEGER\n    DIM errStr AS STRING\n    response, statusCode, errStr = CurlGet(url)\n    \n    IF errStr <> \"\" THEN\n        lblStatus_Text = \"Status: Error - \" & errStr\n        txtResponse.SetValue(\"Error: \" & errStr)\n    ELSE\n        lblStatus_Text = \"Status: Success (HTTP \" & Str(statusCode) & \")\"\n        txtResponse.SetValue(response)\n    ENDIF\nEND SUB\n"
}
