{
  "name": "frmFileDialog",
  "caption": "Open File",
  "width": 71,
  "height": 28,
  "foreColor": 14,
  "backColor": 0,
  "controls": [
    {
      "id": 1,
      "type": 2,
      "name": "lblLookIn",
      "caption": "Look in:",
      "x": 2,
      "y": 1,
      "width": 8,
      "height": 1,
      "foreColor": 15,
      "backColor": 0,
      "tabIndex": 1,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 3,
      "type": 8,
      "name": "fraFolders",
      "caption": "Folders",
      "x": 2,
      "y": 5,
      "width": 31,
      "height": 14,
      "foreColor": 14,
      "backColor": 0,
      "tabIndex": 3,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 4,
      "type": 21,
      "name": "xFolders",
      "caption": "",
      "x": 3,
      "y": 6,
      "width": 29,
      "height": 12,
      "foreColor": 15,
      "backColor": 0,
      "tabIndex": 4,
      "tabStop": true,
      "enabled": true,
      "visible": true,
      "path": "/home/zditech",
      "showHidden": false,
      "linkedPath": "pathCurrent"
    },
    {
      "id": 5,
      "type": 8,
      "name": "fraFiles",
      "caption": "Files",
      "x": 33,
      "y": 5,
      "width": 34,
      "height": 14,
      "foreColor": 14,
      "backColor": 0,
      "tabIndex": 5,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 6,
      "type": 22,
      "name": "xFiles",
      "caption": "",
      "x": 34,
      "y": 6,
      "width": 32,
      "height": 12,
      "foreColor": 15,
      "backColor": 0,
      "tabIndex": 6,
      "tabStop": true,
      "enabled": true,
      "visible": true,
      "path": "/home/zditech",
      "showHidden": false,
      "pattern": "*",
      "linkedPath": "pathCurrent"
    },
    {
      "id": 7,
      "type": 2,
      "name": "lblFilename",
      "caption": "File name:",
      "x": 2,
      "y": 20,
      "width": 10,
      "height": 1,
      "foreColor": 15,
      "backColor": 0,
      "tabIndex": 7,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 8,
      "type": 3,
      "name": "txtFilename",
      "caption": "",
      "x": 13,
      "y": 20,
      "width": 40,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 8,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 9,
      "type": 2,
      "name": "lblFilter",
      "caption": "Files of type:",
      "x": 2,
      "y": 22,
      "width": 13,
      "height": 1,
      "foreColor": 15,
      "backColor": 0,
      "tabIndex": 9,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 10,
      "type": 7,
      "name": "cboFilter",
      "caption": "",
      "x": 16,
      "y": 22,
      "width": 37,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 10,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 11,
      "type": 1,
      "name": "btnOpen",
      "caption": "Open",
      "x": 55,
      "y": 20,
      "width": 12,
      "height": 3,
      "foreColor": 14,
      "backColor": 0,
      "tabIndex": 11,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 12,
      "type": 1,
      "name": "btnCancel",
      "caption": "Cancel",
      "x": 55,
      "y": 24,
      "width": 12,
      "height": 1,
      "foreColor": 14,
      "backColor": 0,
      "tabIndex": 12,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 13,
      "type": 4,
      "name": "chkShowHidden",
      "caption": "Show hidden files",
      "x": 2,
      "y": 24,
      "width": 20,
      "height": 1,
      "foreColor": 15,
      "backColor": 0,
      "tabIndex": 13,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 13,
      "type": 20,
      "name": "xPath",
      "caption": "",
      "x": 12,
      "y": 1,
      "width": 55,
      "height": 3,
      "foreColor": 14,
      "backColor": 0,
      "tabIndex": 14,
      "tabStop": true,
      "enabled": true,
      "visible": true,
      "path": ".",
      "linkedPath": ""
    }
  ],
  "code": "' frmFileDialog Code\n\n                            \n\nSUB frmFileDialog_Load()\n    ' TODO: Add event handler code\n    xPath.LinkedPath = \"dude\"\n    xFolders.LinkedPath = \"dude\"\n    xFiles.LinkedPath = \"dude\"\n    linkedPath(\"dude\", \"/home\")\nEND SUB\n\nSUB frmFileDialog_Unload()\n    ' TODO: Add event handler code\nEND SUB\n\nSUB xFiles_Change()\n    ' TODO: Add event handler code\n    txtFilename.SetText(xPath.Path & \"/\" & xFiles.SelectedFile)\nEND SUB\n"
}