{
  "name": "Form1",
  "caption": "VDBTerm Demo Form",
  "width": 60,
  "height": 28,
  "foreColor": 0,
  "backColor": 7,
  "controls": [
    {
      "id": 0,
      "type": 2,
      "name": "lblTitle",
      "caption": "VDBTerm Demo",
      "x": 2,
      "y": 1,
      "width": 20,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 3,
      "name": "txtInput",
      "caption": "",
      "x": 2,
      "y": 3,
      "width": 25,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 1,
      "name": "btnOK",
      "caption": "OK",
      "x": 2,
      "y": 5,
      "width": 10,
      "height": 3,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 1,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 1,
      "name": "btnCancel",
      "caption": "Cancel",
      "x": 14,
      "y": 5,
      "width": 10,
      "height": 3,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 2,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 4,
      "name": "chkOption",
      "caption": "Enable feature",
      "x": 2,
      "y": 8,
      "width": 18,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 3,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 5,
      "name": "optChoice1",
      "caption": "Option A",
      "x": 2,
      "y": 10,
      "width": 12,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 4,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 5,
      "name": "optChoice2",
      "caption": "Option B",
      "x": 2,
      "y": 11,
      "width": 12,
      "height": 1,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 5,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 6,
      "name": "lstItems",
      "caption": "",
      "x": 30,
      "y": 2,
      "width": 18,
      "height": 8,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 6,
      "tabStop": true,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 8,
      "name": "fraGroup",
      "caption": "Options",
      "x": 28,
      "y": 1,
      "width": 22,
      "height": 10,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 0,
      "tabStop": false,
      "enabled": true,
      "visible": true
    },
    {
      "id": 0,
      "type": 21,
      "name": "xDir",
      "caption": "",
      "x": 1,
      "y": 17,
      "width": 20,
      "height": 9,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 8,
      "tabStop": true,
      "enabled": true,
      "visible": true,
      "path": "/",
      "showHidden": false,
      "linkedControl": ""
    },
    {
      "id": 12,
      "type": 20,
      "name": "xPath",
      "caption": "",
      "x": 1,
      "y": 14,
      "width": 56,
      "height": 3,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 7,
      "tabStop": true,
      "enabled": true,
      "visible": true,
      "path": "/",
      "linkedControl": ""
    },
    {
      "id": 12,
      "type": 22,
      "name": "xFile",
      "caption": "",
      "x": 22,
      "y": 17,
      "width": 35,
      "height": 9,
      "foreColor": 0,
      "backColor": 7,
      "tabIndex": 9,
      "tabStop": true,
      "enabled": true,
      "visible": true,
      "path": ".",
      "showHidden": false,
      "pattern": "*",
      "linkedControl": ""
    }
  ],
  "code": "' Form1 Code - VDBTerm Demo\n\n' This form demonstrates various VDBTerm controls\n' Use arrow keys to move controls, +/- to resize\n' Click with mouse to select and drag controls\n\nSUB Form_Load()\n    ' Initialize form controls\n    lblTitle.Caption = \"Welcome to VDBTerm!\"\nEND SUB\n\nSUB btnOK_Click()\n    ' Handle OK button click\n    lblTitle.Caption = \"Eat Shit!\"\nEND SUB\n\nSUB xPath_Enter()\n    ' TODO: Add event handler code\n    xDir.SetPath(xPath.Path)\n    xDir.View()\n    xFile.SetPath(xPath.Path)\n    xFile.View()\nEND SUB\n\nSUB xDir_Enter()\n    ' TODO: Add event handler code\n    xPath.SetPath(xDir.Path)\n    xPath.View()\n    xFile.SetPath(xDir.Path)\n    xFile.View()\nEND SUB\n\nSUB xDir_Change()\n    ' TODO: Add event handler code\n    xFile.SetPath(xDir.Path)\n    xFile.View()\nEND SUB\n\nSUB xFile_Change()\n    ' TODO: Add event handler code\n    DIM x as integer\n    x = MsgBox(\"Are you sure?\", vbYesNo, \"Confirm\")\n    if x = vbOK then\n        ' OK\n    end if\nEND SUB\n"
}